from __future__ import annotations

from typing import Callable, Protocol, TypeVar

from red_leaf_town.domain import (
    CommissionBoardEntry,
    CommissionPayout,
    MailMessage,
    PlayerState,
    QQIdentity,
    RedemptionCode,
)

T = TypeVar("T")


class PlayerRepository(Protocol):
    def ensure_player(self, oauth_sub: str, display_name: str, now: int) -> PlayerState: ...
    def get_by_sub(self, oauth_sub: str) -> PlayerState | None: ...
    def get(self, player_id: str) -> PlayerState | None: ...
    def search(self, query: str, limit: int = 50) -> list[PlayerState]: ...
    def update(self, player_id: str, mutation: Callable[[PlayerState], T]) -> tuple[PlayerState, T]: ...
    def delete(self, player_id: str) -> bool: ...
    def create_binding_code(self, player_id: str, ttl_seconds: int = 600) -> str: ...
    def consume_binding_code(self, code: str, identity: QQIdentity) -> str | None: ...
    def player_id_for_identity(self, identity: QQIdentity) -> str | None: ...
    def binding_labels(self, player_id: str) -> list[str]: ...


class CommissionBoardRepository(Protocol):
    """公共转发池。玩家存档之外唯一的共享状态，接单必须是原子的。"""

    def publish(self, entry: CommissionBoardEntry) -> None: ...
    def get(self, day: str, commission_id: str) -> CommissionBoardEntry | None: ...
    def list_open(self, day: str, exclude_player_id: str = "", limit: int = 30) -> list[CommissionBoardEntry]: ...
    def withdraw(self, day: str, commission_id: str, owner_id: str) -> CommissionBoardEntry | None: ...
    def take(self, day: str, commission_id: str, taker_id: str, payout: CommissionPayout) -> CommissionBoardEntry | None: ...
    def release(self, day: str, commission_id: str, taker_id: str, payout: CommissionPayout) -> None: ...
    def drain_payouts(self, player_id: str) -> list[CommissionPayout]: ...
    def restore_payouts(self, player_id: str, payouts: list[CommissionPayout]) -> None: ...


class MailRepository(Protocol):
    """公共信箱。全服信只存一份大家共读，个人信按收件人分桶；读没读过记在各自存档里。"""

    def publish(self, mail: MailMessage) -> None: ...
    def get(self, mail_id: str, recipient_id: str = "") -> MailMessage | None: ...
    def list_global(self) -> list[MailMessage]: ...
    def list_for_player(self, player_id: str) -> list[MailMessage]: ...
    def delete(self, mail_id: str, recipient_id: str = "") -> bool: ...


class RedemptionCodeRepository(Protocol):
    """激活码池。兑换必须是原子的，否则同一张码并发提交会被兑两次。"""

    def create(self, codes: list[RedemptionCode]) -> int: ...
    def get(self, code: str) -> RedemptionCode | None: ...
    def claim(self, code: str, player_id: str, now: int) -> RedemptionCode | None: ...
    def release(self, code: str, player_id: str) -> None: ...
    def list_recent(self, limit: int = 200) -> list[RedemptionCode]: ...
