from __future__ import annotations

from typing import Callable, Protocol, TypeVar

from red_leaf_town.domain import PlayerState, QQIdentity

T = TypeVar("T")


class PlayerRepository(Protocol):
    def ensure_player(self, oauth_sub: str, display_name: str, now: int) -> PlayerState: ...
    def get_by_sub(self, oauth_sub: str) -> PlayerState | None: ...
    def get(self, player_id: str) -> PlayerState | None: ...
    def update(self, player_id: str, mutation: Callable[[PlayerState], T]) -> tuple[PlayerState, T]: ...
    def create_binding_code(self, player_id: str, ttl_seconds: int = 600) -> str: ...
    def consume_binding_code(self, code: str, identity: QQIdentity) -> str | None: ...
    def player_id_for_identity(self, identity: QQIdentity) -> str | None: ...
    def binding_labels(self, player_id: str) -> list[str]: ...
